config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "friends#index"
   end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :data)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name,class:"form-control" ,placeholder: "First Name"  %>
  </div>
  <div class="mb-3">
    <%= form.text_field :last_name,class:"form-control",placeholder: "Last Name"  %>
  </div>

  <div class="mb-3">

    <%= form.text_field :initial,class:"form-control" ,placeholder: "Initial" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :phone,class:"form-control",placeholder: "Phone"  %>
  </div>
  <div class="mb-3">

    <%= form.text_field :email,class:"form-control" ,placeholder: "Email" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :address,class:"form-control",placeholder: "Address"  %>
  <div class="mb-3">
    <%# form.text_field :user_id ,id: :friend_user_id,class:"form-control", value:current_user.id , type: :hidden #%>
    
  ></div>
<br/>
  <div class="action">
    <%= form.submit  class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= friend.data %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br/>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show Card", @friend ,class:'btn btn-dark'%> 
  <%= link_to "Back", friends_path,class:'btn btn-dark' %>
</div>

app/views/friends/index.html.erb
<h1>Friend list</h1>
<table class="table table-striped table-hover">
 <thead class="thread-dark">
  <tr>
    <th>Name</th>

    <th>Number</th>
    <th>Email</th>
  </tr>

 </thead>
    
<!--div id="friends" -->
<tbody >

<% @friends.each do |friend| %>
  <tr>
    <td><%= link_to friend.first_name.capitalize + ' ' + friend.last_name.capitalize, friend %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.email.capitalize %></td>
  </tr>
<% end %>

</tbody>
  </div>

  </table>

<%= link_to "New friend", new_friend_path,class:"btn btn-secondary" %>

<%= yield %>

app/views/friends/new.html.erb
<h1>New friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path , class:"btn btn-dark"%>
</div>

app/views/friends/show.html.erb
<div class="card text-bg-secondary mb-3 card-body p-3 m-0 border-0 bd-example m-0 border-0">
<h5 class="card-title"> <%= @friend.first_name %> <%= @friend.last_name %></h5>
      <p class="card-text"><%=@friend.phone %></p>
   <p class="card-text"><%=@friend.email.capitalize %></p>

  <!-- <p><%= @friend.phone %></p>
   <p><%= @friend.phone %></p>-->
 </div>
<div class="card-textp-3 m-0 border-0 bd-example m-0 border-0">
  <%= link_to "Edit", edit_friend_path(@friend) ,class:"btn btn-secondary"%>
  <%= link_to "Back", friends_path ,class:"btn btn-secondary"%>
  <br/>
</br>
  <%= button_to "Destroy", @friend, method: :delete ,class:"btn btn-outline-danger"%>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to "Friend App" ,root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	< a class:"nav-link"> About</a>	
        </li>
        
        <% if user_signed_in? %>
        <li class="nav-item">
        	<%= link_to "Show Friends" ,friends_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
        	<%= link_to "Add Friend" ,new_friend_path,class:"nav-link"%>	
        </li>
        <li class="nav-item">
        	<li class="nav-item">
        	<%= link_to "Edit profile" ,edit_user_registration_path,class:"nav-link"%>	
        </li>
        	<%= button_to "Sign Out" ,destroy_user_session_path, method: :delete ,class:"btn btn-outline-success" %>	
        </li>
        <% else %> 
        <li class="nav-item">
        	<%= link_to "Sign Up" ,new_user_registration_path,class:"nav-link"%>	
        </li>
        <li class="nav-item">
        	<%= link_to "Sign in" ,new_user_session_path,class:"nav-link"%>	
        </li>
        <%end%>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/cards.html.erb
<h1>Cards </h1>

app/views/home/index.html.erb
<h1>Meow</h1>
<p></p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <strong>!</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <br/>
    <% if notice %>
    <%= render 'layouts/alerts'%>
   <% end%>
    <%= render'home/header'%>
    <div class="container">
      </br>
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

 
    
  </body>
</html>